### ISSUE TITLE
Braindump Freezes When Trying To Dump Pokemon Sun

### ISSUE THREAD

**Issue by MidgeThePidge** [neobrain/braindump#33]
It gets stuck on a red screen when trying to load braindump.

**Comment by Arytor** [comment]
For me it didn't did that. But the problem is when extacting. It's taking 4 days to extract the RomFS.

**Comment by neobrain** [comment]
IIRC other people have said braindump only supports dumping physical copies of this game. Either way, red screen indicates the title you are trying to dump is not supported by HANS, and as such not by braindump either since it's using the same underlying mechanism.

If you can, you may have more luck using GodMode9 instead of braindump.
